version: '3.4'

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports: 
        - 8082:80
        - 5341:5341
    environment:
        ACCEPT_EULA: Y

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      #test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 15s
      retries: 3

  redis:
    container_name: redis
    image: redis:latest
    ports:
        - 6379:6379

  dockerpoc.catalog:
    container_name: catalogapi
    image: ${DOCKER_REGISTRY-}dockerpoccatalog
    build:
      context: .
      dockerfile: DockerPOC.Catalog/Dockerfile
    ports:
       - 8080:80
    restart: on-failure
    depends_on:
       seq:
        condition: service_started
       redis:
        condition: service_started
       rabbitmq:
        condition: service_healthy

  dockerpoc.ordering:
    container_name: orderingapi
    image: ${DOCKER_REGISTRY-}dockerpocordering
    build:
      context: .
      dockerfile: DockerPOC.Ordering/Dockerfile
    ports:
       - 8081:80
    depends_on:
       - rabbitmq